#include "sim.hpp"
#include "oracle_trace.hpp"
#include "prefetchers.hpp"

#include <algorithm>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
using namespace lapsim;
namespace {
struct Args{std::string trace,name="trace",prefetcher="none";Bytes capacity=256ULL*1024*1024;std::vector<Time>latencies_us{0,1000,5000,10000,20000};std::uint64_t limit=0;Time ticks_per_second=1000000;bool spread_within_second=true;};
std::vector<Time> parse_latencies(const std::string&t){std::vector<Time>o;std::stringstream ss(t);std::string x;while(std::getline(ss,x,',')){if(x.empty())continue;auto v=std::stoll(x);if(v<0)throw std::invalid_argument("negative latency");o.push_back(v);}if(o.empty())throw std::invalid_argument("no latency");if(std::find(o.begin(),o.end(),0)==o.end())o.insert(o.begin(),0);return o;}
Args parse_args(int n,char**v){Args a;for(int i=1;i<n;++i){std::string s=v[i];auto need=[&](){if(i+1>=n)throw std::invalid_argument("missing value for "+s);return std::string(v[++i]);};if(s=="--trace")a.trace=need();else if(s=="--name")a.name=need();else if(s=="--prefetcher")a.prefetcher=need();else if(s=="--capacity")a.capacity=std::stoull(need());else if(s=="--latencies-us")a.latencies_us=parse_latencies(need());else if(s=="--limit")a.limit=std::stoull(need());else if(s=="--ticks-per-second")a.ticks_per_second=std::stoll(need());else if(s=="--time-model"){auto x=need();if(x=="spread")a.spread_within_second=true;else if(x=="raw")a.spread_within_second=false;else throw std::invalid_argument("time model must be spread or raw");}else throw std::invalid_argument("unknown argument: "+s);}if(a.trace.empty())throw std::invalid_argument("usage: trace_bench --trace FILE [--prefetcher none|obl|stride|pg]");return a;}
struct Scenario{Time latency_us;Simulator sim;Scenario(Time l,Bytes c):latency_us(l),sim(Simulator::fixed_lru(c,l)){}};
void js(std::ostream&o,const std::string&s){o<<'"';for(char c:s){if(c=='\\')o<<"\\\\";else if(c=='"')o<<"\\\"";else o<<c;}o<<'"';}
}
int main(int argc,char**argv){try{auto a=parse_args(argc,argv);auto pf=make_prefetcher(a.prefetcher);std::ifstream f;std::istream*in;if(a.trace=="-")in=&std::cin;else{f.open(a.trace,std::ios::binary);if(!f)throw std::runtime_error("cannot open trace");in=&f;}ByteLru instant(a.capacity);std::vector<Scenario>sc;for(auto l:a.latencies_us)sc.emplace_back(l,a.capacity);std::uint64_t requests=0,demand_bytes=0,instant_hits=0,instant_miss_bytes=0,buckets=0,max_bucket=0,predictions=0;bool have_first=false;std::uint32_t first_clock=0,last_clock=0;Time last_arrival=0;std::vector<OracleRecord>b;b.reserve(4096);
auto process=[&](const std::vector<OracleRecord>&r){if(r.empty())return;++buckets;max_bucket=std::max<std::uint64_t>(max_bucket,r.size());auto clock=r.front().clock_time;if(!have_first){first_clock=clock;have_first=true;}auto base=static_cast<Time>(clock-first_clock)*a.ticks_per_second;for(std::size_t k=0;k<r.size();++k){auto&x=r[k];if(!x.size||x.size>a.capacity)throw std::runtime_error("bad object size");Time arrival=base;if(a.spread_within_second)arrival+=static_cast<Time>((static_cast<__int128>(k+1)*a.ticks_per_second)/(r.size()+1));if(arrival<last_arrival)throw std::runtime_error("time moved backwards");last_arrival=arrival;++requests;demand_bytes+=x.size;bool hit=instant.on_demand(x.object,x.size,arrival);if(hit)++instant_hits;else{instant_miss_bytes+=x.size;instant.on_fill(x.object,x.size,arrival,FetchOrigin::Demand);}Request q{arrival,x.object,x.size};for(auto&s:sc)s.sim.demand(q);auto ps=pf->on_demand(q);predictions+=ps.size();for(auto&p:ps)for(auto&s:sc)s.sim.prefetch(arrival,p.object,p.size);}last_clock=clock;};
OracleRecord x;bool hb=false;std::uint32_t bc=0;while((!a.limit||requests+b.size()<a.limit)&&read_oracle_record(*in,x)){if(!hb){bc=x.clock_time;hb=true;}if(x.clock_time<bc)throw std::runtime_error("timestamps not nondecreasing");if(x.clock_time!=bc){process(b);b.clear();if(a.limit&&requests>=a.limit)break;bc=x.clock_time;}if(!a.limit||requests+b.size()<a.limit)b.push_back(x);}process(b);if(!requests)throw std::runtime_error("empty trace");double ref=double(instant_hits)/requests;std::cout<<std::setprecision(15)<<"{\"trace\":";js(std::cout,a.name);std::cout<<",\"prefetcher\":";js(std::cout,pf->name());std::cout<<",\"requests\":"<<requests<<",\"predictions\":"<<predictions<<",\"demand_bytes\":"<<demand_bytes<<",\"capacity_bytes\":"<<a.capacity<<",\"time_model\":";js(std::cout,a.spread_within_second?"spread":"raw");std::cout<<",\"coarse_buckets\":"<<buckets<<",\"max_requests_in_second\":"<<max_bucket<<",\"first_clock\":"<<first_clock<<",\"last_clock\":"<<last_clock<<",\"instant_lru_hit_ratio\":"<<ref<<",\"instant_lru_miss_bytes\":"<<instant_miss_bytes<<",\"scenarios\":[";bool first=true;for(auto&s:sc){auto&m=s.sim.metrics();if(!first)std::cout<<',';first=false;double n=m.demands;double resident=n?m.resident_hits/n:0,delayed=n?m.prefetch_delayed_hits/n:0,coal=n?m.demand_coalesced_hits/n:0,noio=n?(m.resident_hits+m.prefetch_delayed_hits+m.demand_coalesced_hits)/n:0;std::cout<<"{\"latency_us\":"<<s.latency_us<<",\"resident_hit_ratio\":"<<resident<<",\"prefetch_delayed_ratio\":"<<delayed<<",\"demand_coalesced_ratio\":"<<coal<<",\"new_misses\":"<<m.new_misses<<",\"served_without_new_io_ratio\":"<<noio<<",\"backend_fetches\":"<<m.backend_fetches<<",\"backend_bytes\":"<<m.backend_bytes<<",\"average_access_time_us\":"<<m.average_access_time()<<",\"prefetch_fetches\":"<<m.prefetch_fetches<<",\"prefetch_bytes\":"<<m.prefetch_bytes<<",\"redundant_prefetch_resident\":"<<m.redundant_prefetch_resident<<",\"redundant_prefetch_inflight\":"<<m.redundant_prefetch_inflight<<",\"suppressed_prefetch_oversize\":"<<m.suppressed_prefetch_oversize;if(s.latency_us>0)std::cout<<",\"aat_fraction_of_backend_latency\":"<<m.average_access_time()/double(s.latency_us);std::cout<<"}";}std::cout<<"]}\n";if(a.prefetcher=="none"){auto z=std::find_if(sc.begin(),sc.end(),[](auto&s){return s.latency_us==0;});auto&m=z->sim.metrics();if(m.resident_hits!=instant_hits||m.new_misses!=requests-instant_hits)throw std::runtime_error("zero-latency LRU mismatch");}return 0;}catch(const std::exception&e){std::cerr<<"trace_bench: "<<e.what()<<'\n';return 2;}}
